# .travis.yml

# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
xcode_sdk: macosx10.11
xcode_project: XCode/SwiftDate.xcodeproj
xcode_scheme: SwiftDate
before_install:
- export LANG=en_US.UTF-8
- env
- locale
- brew update
- brew upgrade carthage 
- brew install swiftlint
- carthage update --project-directory XCode --platform osx
after_success:
- swiftlint --path Sources/SwiftDate
- pod lib lint
